@host=http://localhost:4000
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZmZkNmFmMzdkZTEyODM0YjcyODk1NGEiLCJyb2xlIjpbIkFHRU5DWV9PV05FUiJdLCJpYXQiOjE2MTA0NzE2NjgsImV4cCI6MTYxMTA3NjQ2OH0.qtgaxdBcMoPxAKufgxuEn4AMNMXBc6M39KvMVl1NNYw

GET {{host}}/api/users/login
Content-Type: application/json

{
    "email": "zarar6@test.com",
    "password": "Test1234"
}

###
POST {{host}}/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "Zorro Ahmed",
    "email": "zarar6@test.com",
    "password": "Test1234"
}

###
GET {{host}}/api/posts
Content-Type: application/json

{
    "email": "zarar6@test.com",
    "password": "Test1234"
}

###
POST {{host}}/api/posts
Content-Type: application/json
Authorization: {{token}}

{
    "email": "zarar6@test.com",
    "password": "Test1234",
    "role": ["AGENCY_OWNER"]
}













###
GET {{host}}/api/opportunities/count HTTP/1.1


###
DELETE {{host}}/api/users/5fd89f75d050811c5f98cc65

###
POST {{host}}/api/users/ HTTP/1.1
Content-Type: application/json
Authorization: {{token}}
{
    "name": "Zorro Ahmed",
    "createdBy":"zararahmed",
    "email": "zarar1@test.com",
    "password": "Test1234",
    "roles": ["SYSTEM_ADMINISTRATOR", "AGENCY_OWNER", "MAINTAINER"]
}

# Authorization: {{token}}